config/routes.rb
Rails.application.routes.draw do
  resources :subderrits do
    resources :posts do
      post '/upvote' => 'posts#upvote'
      post '/downvote' => 'posts#downvote'
      delete '/vote' => 'posts#delete_vote'
      put '/vote' => 'posts#edit_vote'
      resources :comments, only: [:show, :create, :edit, :update, :destroy] do
        resources :comments, only: [:show, :new, :create, :update, :destroy]
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
          delete '/vote' => 'comments#delete_vote'
          put '/vote' => 'comments#edit_vote'
      end

    end
  end
  resources :users, except: [:new, :create, :index, :edit]

  root 'subderrits#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/all' => 'posts#index'

end

app/models/subderrit.rb
# "Subreddit" class
class Subderrit < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :moderators, presence: true
  validates :moderators, length: { minimum: 1 }

  has_many :users_subderrits, dependent: :destroy
  has_many :users, through: :users_subderrits
  has_many :posts, dependent: :destroy
  serialize :moderators, Array
  serialize :blacklist, Array
end

app/controllers/subderrits_controller.rb
# Subderrits Controller
class SubderritsController < ApplicationController
  before_action :set_subderrit, only: [:show, :edit, :update, :destroy]

  # GET /subderrits
  # GET /subderrits.json
  def index
    @subderrits = Subderrit.all
  end

  # GET /subderrits/1
  # GET /subderrits/1.json
  def show
  end

  # GET /subderrits/new
  def new
    @subderrit = Subderrit.new
  end

  # GET /subderrits/1/edit
  # Maybe later

  # def edit
  # end

  # POST /subderrits
  # POST /subderrits.json
  def create
    user = current_user
    @subderrit = user.subderrits.create(subderrit_params)
    @subderrit.moderators << current_user.username
    respond_to do |format|
      if @subderrit.save

        format.html { redirect_to @subderrit, notice: 'Subderrit was successfully created.' }
        format.json { render :show, status: :created, location: @subderrit }
      else
        format.html { render :new }
        format.json { render json: @subderrit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subderrits/1
  # PATCH/PUT /subderrits/1.json
  def update
    respond_to do |format|
      if @subderrit.update(subderrit_params)
        format.html { redirect_to @subderrit, notice: 'Subderrit was successfully updated.' }
        format.json { render :show, status: :ok, location: @subderrit }
      else
        format.html { render :edit }
        format.json { render json: @subderrit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subderrits/1
  # DELETE /subderrits/1.json
  def destroy
    @subderrit.destroy
    respond_to do |format|
      format.html { redirect_to subderrits_url, notice: 'Subderrit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_subderrit
    @subderrit = Subderrit.find(params[:id])
  end

  def subderrit_params
    params.require(:subderrit).permit(:name)
  end
end

app/helpers/subderrits_helper.rb
module SubderritsHelper
end

app/views/subderrits/_form.html.erb
<%= form_for(@subderrit) do |f| %>
  <% if @subderrit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subderrit.errors.count, "error") %> prohibited this subderrit from being saved:</h2>

      <ul>
      <% @subderrit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subderrits/edit.html.erb
<h1>Editing Subderrit</h1>

<%= render 'form' %>

<%= link_to 'Show', @subderrit %> |
<%= link_to 'Back', subderrits_path %>

app/views/subderrits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subderrits:</h1>

<table>

  <tbody>
    <td> <%= link_to "All", "/all" %> </td>
    <% @subderrits.each do |subderrit| %>
      <tr>
        <td><%= link_to "#{subderrit.name}", subderrit %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? %>
  <%= link_to 'Make your own!', new_subderrit_path %>
<%end%>

app/views/subderrits/new.html.erb
<h1>New Subderrit</h1>

<%= render 'form' %>

<%= link_to 'Back', subderrits_path %>

app/views/subderrits/show.html.erb
<p id="notice"><%= notice %></p>

<% if logged_in? %>
<% is_moderator = @subderrit.moderators.include?(current_user.username)%>
<% end %>
<p>
  <center><h2><%= @subderrit.name %></h2></center>
</p>


Moderators:</br>
<% @subderrit.moderators.each do |mod|%>
<%=mod%></br>
<%end%>


<h3>Posts:</h3>
<% @subderrit.posts.order(net_votes: :desc).each do |post|%>
  <p>

  <%= post.net_votes%>
  <%=link_to "#{post.title}", subderrit_post_path(subderrit_id: params[:id], id: post.id)%>
  by:
  <%= link_to post.user.username, user_path(post.user.id)%>
  <% if logged_in? %>
    <% vote = Pvote.where(post_id: post.id, user_id: current_user.id).first%>
    <% if post.user_id != current_user.id %>
      <% if vote %>
        <% if vote.value == 1 %>
          <%= button_to 'Upvote', subderrit_post_vote_path(subderrit_id: params[:id], post_id: post.id), method: :delete%>
          <%= button_to 'Downvote', "/subderrits/#{params[:id]}/posts/#{post.id}/vote", method: :put%>
        <% elsif vote.value == -1 %>
          <%= button_to 'Upvote', "/subderrits/#{params[:id]}/posts/#{post.id}/vote", method: :put%>
          <%= button_to 'Downvote', subderrit_post_vote_path(subderrit_id: params[:id], post_id: post.id), method: :delete%>
        <% end %>
      <% else %>
        <%= button_to 'Upvote', subderrit_post_upvote_path(subderrit_id: params[:id], post_id: post.id)%>
        <%= button_to 'Downvote', subderrit_post_downvote_path(subderrit_id: params[:id], post_id: post.id)%>
      <% end %>
    <% end %>

    <% if is_moderator || post.user == current_user %>
      <%= button_to 'Delete Post', "/subderrits/#{params[:id]}/posts/#{post.id}", method: :delete %>
    <% end %>
  <% end %>
  </p>
<%end%>


<% if is_moderator %>
<%= link_to 'Delete Subderrit', @subderrit, method: :delete, data: { confirm: 'Are you sure?' } %></br></td>
<% end %>
<% if logged_in? %>
<%= link_to 'Make Post', "/subderrits/#{@subderrit.id}/posts/new" %></br>
<% end %>