config/routes.rb
Rails.application.routes.draw do
  resources :subderrits do
    resources :posts do
      post '/upvote' => 'posts#upvote'
      post '/downvote' => 'posts#downvote'
      delete '/vote' => 'posts#delete_vote'
      put '/vote' => 'posts#edit_vote'
      resources :comments, only: [:show, :create, :edit, :update, :destroy] do
        resources :comments, only: [:show, :new, :create, :update, :destroy]
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
          delete '/vote' => 'comments#delete_vote'
          put '/vote' => 'comments#edit_vote'
      end

    end
  end
  resources :users, except: [:new, :create, :index, :edit]

  root 'subderrits#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/all' => 'posts#index'

end

app/models/comment.rb
# Users comment on posts
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :op_comment, :class_name => "Comment"
  has_many :replies, :class_name => "Comment", dependent: :destroy
  has_many :cvotes
end

app/controllers/comments_controller.rb
# Comments controller
class CommentsController < ApplicationController
  # GET /comments/1
  def show
  end

  # GET /comments/1/comments/new
  def new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.net_votes = 0
    if comment_params[:op_comment_id]
      op_comment = Comment.find(comment_params[:op_comment_id])
      @comment.user = current_user
      @comment.save
      op_comment.replies << @comment
      op_comment.save
    else 
      @comment.save
    end
    redirect_to subderrit_post_path(:subderrit_id => params[:subderrit_id], :id => params[:post_id])
  end

  # PATCH/PUT /comments/1
  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to subderrit_post_path(:subderrit_id => params[:subderrit_id], :id => @comment.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /comments/1
  def destroy
    comment = Comment.find(params[:comment_id])
    comment.destroy
    respond_to do |format|
      format.html { redirect_to subderrit_post_path(:id => params[:post_id], :subderrit_id => params[:subderrit_id]), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @comment = Comment.find(params[:comment_id])
    cvote = Cvote.new
    cvote.value = 1
    cvote.comment = @comment
    cvote.user = current_user
    cvote.save
    redirect_to subderrit_post_path(:id => params[:post_id])
  end

  def downvote
    @comment = Comment.find(params[:comment_id])
    cvote = Cvote.new
    cvote.value = -1
    cvote.comment = @comment
    cvote.user = current_user
    cvote.save
    redirect_to subderrit_post_path(:id => params[:post_id])
  end

  def delete_vote
    Cvote.where(user_id: current_user.id, comment_id: params[:comment_id]).destroy_all
    redirect_to subderrit_post_path(:id => params[:post_id])
  end

  def edit_vote
    cvote = Cvote.where(user_id: current_user.id, comment_id: params[:comment_id]).first
    cvote.value = cvote.value * -1
    cvote.save
    redirect_to subderrit_post_path(:id => params[:post_id])
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id, :op_comment_id)
  end
end

app/views/comments/edit.html.erb
<%= form_tag(subderrit_post_comment_path(@comment, :id => params[:post_id], :post_id => params[:post_id]), method: :put) do %>
  <div class="field">
    <%= text_area_tag 'comment[body]', @comment.body %>
  </div>

  <%= hidden_field_tag 'comment[post_id]', params[:id]%>

  <div class="action">
    <%= submit_tag 'Edit' %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<% op_comment = Comment.find(params[:comment_id]) %>
<p>
Original Comment:
</br><%= op_comment.body %>
</p>

<%= form_tag(subderrit_post_comment_comments_path(@comment, :comment_id => params[:comment_id], :post_id => params[:post_id], :subderrit_id => params[:subderrit_id])) do %>

  <div class="field">
    <%= label_tag :body %>
    <%= text_area_tag 'comment[body]' %>
  </div>

  <%= hidden_field_tag 'comment[post_id]', params[:post_id]%>
  <%= hidden_field_tag 'comment[op_comment_id]', params[:comment_id] %>

  <div class="action">
    <%= submit_tag %>
  </div>


<% end %>

<%= link_to 'Back', subderrit_posts_path %>