config/routes.rb
Rails.application.routes.draw do
  resources :subderrits do
    resources :posts do
      post '/upvote' => 'posts#upvote'
      post '/downvote' => 'posts#downvote'
      delete '/vote' => 'posts#delete_vote'
      put '/vote' => 'posts#edit_vote'
      resources :comments, only: [:show, :create, :edit, :update, :destroy] do
        resources :comments, only: [:show, :new, :create, :update, :destroy]
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
          delete '/vote' => 'comments#delete_vote'
          put '/vote' => 'comments#edit_vote'
      end

    end
  end
  resources :users, except: [:new, :create, :index, :edit]

  root 'subderrits#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/all' => 'posts#index'

end

app/models/post.rb
# Post that's in a subderrit
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :subderrit
  has_many :pvotes
  has_many :comments
end

app/controllers/posts_controller.rb
# Posts Controller
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.net_votes = 0
    respond_to do |format|
      if @post.save
        format.html { redirect_to subderrit_post_path(:subderrit_id => params[:subderrit_id], :id => @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to subderrit_post_path(:subderrit_id => params[:subderrit_id], :id => @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to subderrit_path(:id => params[:subderrit_id]), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:post_id])
    pvote = Pvote.new
    pvote.value = 1
    pvote.post = @post
    pvote.user = current_user
    pvote.save
    redirect_to Subderrit.find(params[:subderrit_id])
  end

  def downvote
    @post = Post.find(params[:post_id])
    pvote = Pvote.new
    pvote.value = -1
    pvote.post = @post
    pvote.user = current_user
    pvote.save
    redirect_to Subderrit.find(params[:subderrit_id])
  end

  def delete_vote
    Pvote.where(user_id: current_user.id, post_id: params[:post_id]).destroy_all
    redirect_to Subderrit.find(params[:subderrit_id])
  end

  def edit_vote
    pvote = Pvote.where(user_id: current_user.id, post_id: params[:post_id]).first
    pvote.value = pvote.value * -1
    pvote.save
    redirect_to Subderrit.find(params[:subderrit_id])
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :subderrit_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_tag(subderrit_post_comments_path(@comment, :post_id => params[:id], :subderrit_id => params[:subderrit_id])) do %>

  <div class="field">
    <%= text_area_tag 'comment[body]' %>
  </div>

  <%= hidden_field_tag 'comment[post_id]', params[:id]%>

  <div class="action">
    <%= submit_tag 'Post' %>
  </div>
<% end %>

app/views/posts/_comment_partial.html.erb
</br>
<%(0..margin).each do |i| %>
>
<%end%>

<strong><%=comment.user.username%></strong></br>

<%(0..margin).each do |i| %>
>
<%end%>

<%=comment.body%></br>
<%= render 'vote_partial', comment: comment %>
<%(0..margin).each do |i| %>
  >
<%end%>
upvotes: <%= comment.net_votes %></br>

<% if logged_in? %>
  <%(0..margin).each do |i| %>
    >
  <%end%>
  <%= link_to 'reply', new_subderrit_post_comment_comment_path(:comment_id => comment.id, :post_id => params[:id], :subderrit_id => params[:subderrit_id]) %>
  <%if @can_delete || comment.user == current_user%>
  </br>
    <%(0..margin).each do |i| %>
      >
    <%end%>
    <%= link_to 'delete', subderrit_post_comment_path(:comment_id => comment.id, :post_id => params[:id]), method: :delete %>
  <%end%>


  <% if current_user == comment.user %>
    </br>
    <%(0..margin).each do |i| %>
      >
    <%end%>
    <%= link_to 'edit', edit_subderrit_post_path %>
  <% end %>
<%end%>


<% comment.replies.order(net_votes: :desc).each do |reply| %>
  <%= render 'comment_partial', margin: margin+1, comment: reply %>
<%end%>

app/views/posts/_edit_form.html.erb
<%= form_for @post, :url => " /subderrits/#{params[:subderrit_id]}/posts/#{@post.id}" do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :subderrit_id, :value => params[:subderrit_id] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, :url => " /subderrits/#{params[:subderrit_id]}/posts" do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :subderrit_id, :value => params[:subderrit_id] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_vote_partial.html.erb
<% if logged_in? %>
  <% vote = Cvote.where(comment_id: comment.id, user_id: current_user.id).first%>
  <% if comment.user_id != current_user.id %>
    <% if vote %>
      <% if vote.value == 1 %>
        <%= button_to 'Upvote', subderrit_post_comment_vote_path(subderrit_id: params[:subderrit_id], post_id: params[:id], comment_id: comment.id), method: :delete%>
        <%= button_to 'Downvote', "/subderrits/#{params[:subderrit_id]}/posts/#{params[:id]}/comments/#{comment.id}/vote", method: :put%>
      <% elsif vote.value == -1 %>
        <%= button_to 'Upvote', "/subderrits/#{params[:subderrit_id]}/posts/#{params[:id]}/comments/#{comment.id}/vote", method: :put%>
        <%= button_to 'Downvote', subderrit_post_comment_vote_path(subderrit_id: params[:subderrit_id], post_id: params[:id], comment_id: comment.id), method: :delete%>
      <% end %>
    <% else %>
      <%= button_to 'Upvote', subderrit_post_comment_upvote_path(:comment_id => comment.id, :post_id => params[:id])%>
      <%= button_to 'Downvote', subderrit_post_comment_downvote_path(:comment_id => comment.id, :post_id => params[:id])%>
    <% end %>
  <% end %>
<%end%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'edit_form' %>

<%= link_to 'Back', subderrit_post_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>All</h1></center>

<h3>Posts:</h3>
<% @posts.order(net_votes: :desc).each do |post|%>
<p>

<%= post.net_votes%>
<%=link_to "#{post.title}", subderrit_post_path(subderrit_id: post.subderrit.id, id: post.id)%>
by:
<%= link_to post.user.username, user_path(post.user.id)%>
in:
<%= link_to post.subderrit.name, subderrit_path(post.subderrit.id) %>

<% if logged_in? %>
  <% vote = Pvote.where(post_id: post.id, user_id: current_user.id).first%>
  <% if post.user_id != current_user.id %>
    <% if vote %>
      <% if vote.value == 1 %>
        <%= button_to 'Upvote', subderrit_post_vote_path(subderrit_id: post.subderrit.id, post_id: post.id), method: :delete%>
        <%= button_to 'Downvote', "/subderrits/#{params[:id]}/posts/#{post.id}/vote", method: :put%>
      <% elsif vote.value == -1 %>
        <%= button_to 'Upvote', "/subderrits/#{params[:id]}/posts/#{post.id}/vote", method: :put%>
        <%= button_to 'Downvote', subderrit_post_vote_path(subderrit_id: post.subderrit.id, post_id: post.id), method: :delete%>
      <% end %>
    <% else %>
      <%= button_to 'Upvote', subderrit_post_upvote_path(subderrit_id: post.subderrit.id, post_id: post.id)%>
      <%= button_to 'Downvote', subderrit_post_downvote_path(subderrit_id: post.subderrit.id, post_id: post.id)%>
    <% end %>
  <% end %>
<% end %>

<% if post.user == current_user %>
  <%= button_to 'Delete Post', "/subderrits/#{post.subderrit.id}/posts/#{post.id}", method: :delete %>
<% end %>

</p>
<%end%>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', subderrit_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @post.title %></h2>
</p>

<p>
  <%= @post.body %></br>
  By: <%= @post.user.username %></br>
  Upvotes: <%= @post.net_votes %>
  <% if current_user == @post.user %>
    </br><%= link_to 'edit', edit_subderrit_post_path %>
  <% end %>
</p>
<%if logged_in? %>
  <% @can_delete = @post.subderrit.moderators.include?(current_user.username) %>



  Make a comment:
  <p>
  <%= render 'comment_form' %>
  </p>
<% end %>

<% @post.comments.order(net_votes: :desc).each do |comment| %>
  <% if comment.op_comment.nil? %>
  
  
  </br><strong><%= comment.user.username %></strong>
  </br><%= comment.body %>
  </br>Upvotes: <%= comment.net_votes %>

  <%= render 'vote_partial', comment: comment%>
  <% if logged_in? %>
    </br><%= link_to 'reply', new_subderrit_post_comment_comment_path(:comment_id => comment.id, :post_id => params[:id], :subderrit_id => params[:subderrit_id]) %>
  <% if @can_delete || comment.user == current_user%>
    </br><%= link_to 'delete', subderrit_post_comment_path(:comment_id => comment.id, :post_id => params[:id]), method: :delete %>
    </br><%= link_to 'edit', edit_subderrit_post_comment_path(:post_id => params[:id])%>
  <%end%>  

  <% end %>
  <%comment.replies.order(net_votes: :desc).each do |nc| %>
    <%= render 'comment_partial', margin: 0, comment: nc %>
  <%end%>
<%end%>


<%end%> 